services:

  postgres:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-vacation_sheet_db}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
#     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?POSTGRES_PASSWORD must be set}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres} # TODO ???
      POSTGRES_HOST_AUTH_METHOD: trust # TODO ???
    ports:
      - 5432:5432
    volumes:
      - ./docker-deploy/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql:Z  # TODO ?
      - postgres-data:/var/lib/postgresql/data:Z
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 12

  vacation-sheet-service:
#    uncomment image and comment build - one only allow
#    image: ghcr.io/kit-1414/vacation_sheet-service:release_v_1.2.3
    build:
      context: .
      dockerfile: vacation-sheet-service/Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB:-vacation_sheet_db}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER:-vacation_sheet}
#      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD:?POSTGRES_PASSWORD must be set}
#      YANDEX_CLIENT_ID: ${YANDEX_CLIENT_ID:?YANDEX_CLIENT_ID must be set}
#      YANDEX_CLIENT_SECRET: ${YANDEX_CLIENT_SECRET:?YANDEX_CLIENT_SECRET must be set}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD:-postgres}  # TODO ?
      YANDEX_CLIENT_ID: ${YANDEX_CLIENT_ID:-2e08121a2d624f80b793ead6eeb9a365} # TODO ?
      YANDEX_CLIENT_SECRET: ${YANDEX_CLIENT_SECRET:-09e6fc1c4bcd43b69aaa1f427ef31d0f} # TODO ?
      YANDEX_REDIRECT_URI: ${YANDEX_REDIRECT_URI:-http://localhost:8055/login/oauth2/code/yandex}
      APP_FRONTEND_URL: ${APP_FRONTEND_URL:-http://localhost:4200}
      APP_BACK_PORT_NUM: ${APP_BACK_PORT_NUM:-8055}
      APP_FRONT_PORT_NUM: ${APP_FRONT_PORT_NUM:-4200}
      APP_SECURITY_ALLOWED_EMAIL_DOMAIN: ${ALLOWED_EMAIL_DOMAIN:-}
    ports:
      - ${APP_BACK_PORT_NUM:-8055}:${APP_BACK_PORT_NUM:-8055}
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "--fail", "--silent", "http://localhost:${APP_BACK_PORT_NUM:-8055}/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 12

  vacation-sheet-ui:
    build:
      context: vacation-sheet-ui
    ports:
      - ${APP_FRONT_PORT_NUM:-4200}:80
    depends_on:
      vacation-sheet-service:
        condition: service_healthy

volumes:
  postgres-data:
