CREATE TABLE user_accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(320) NOT NULL UNIQUE CHECK (email = lower(btrim(email))),
    first_name VARCHAR(255),
    last_name VARCHAR(255),
    is_admin BOOLEAN NOT NULL DEFAULT FALSE,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    ctime TIMESTAMP WITH TIME ZONE NOT NULL,
    utime TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE projects (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          name VARCHAR(100) NOT NULL CHECK (name = btrim(name) AND name ~ '^[A-Za-z0-9]+$'),
    description VARCHAR(1000),
    ctime TIMESTAMP WITH TIME ZONE NOT NULL,
    utime TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE UNIQUE INDEX projects_name_lower_uq ON projects (lower(name));

CREATE TABLE project_members (
                                 project_id BIGINT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
                                 user_account_id BIGINT NOT NULL REFERENCES user_accounts(id) ON DELETE CASCADE,
                                 PRIMARY KEY (project_id, user_account_id)
);

CREATE INDEX project_members_user_account_id_idx ON project_members(user_account_id);

CREATE TABLE project_manager (
                                 project_id BIGINT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
                                 user_account_id BIGINT NOT NULL REFERENCES user_accounts(id) ON DELETE CASCADE,
                                 PRIMARY KEY (project_id, user_account_id)
);

CREATE INDEX project_manager_user_account_id_idx ON project_manager(user_account_id);

CREATE TABLE vacation_requests (
                                   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                   title VARCHAR(50) NOT NULL CHECK (title = btrim(title) AND title <> ''),
                                   request_state VARCHAR(20) NOT NULL CHECK (request_state IN ('DRAFT', 'READY', 'APPROVED', 'REJECTED')),
                                   vacation_type VARCHAR(30) NOT NULL CHECK (vacation_type IN ('PAYMENT_VACATION', 'FREE_VACATION')),
                                   start_date DATE NOT NULL,
                                   end_date DATE NOT NULL CHECK (end_date >= start_date),
                                   user_comments VARCHAR(2000),
                                   manager_comments VARCHAR(2000),
                                   author_id BIGINT NOT NULL REFERENCES user_accounts(id) ON DELETE CASCADE,
                                   manager_id BIGINT REFERENCES user_accounts(id) ON DELETE SET NULL,
                                   ctime TIMESTAMP WITH TIME ZONE NOT NULL,
                                   utime TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX vacation_requests_author_id_idx ON vacation_requests(author_id);
CREATE INDEX vacation_requests_manager_id_idx ON vacation_requests(manager_id);
CREATE INDEX vacation_requests_request_state_idx ON vacation_requests(request_state);
CREATE INDEX vacation_requests_vacation_type_idx ON vacation_requests(vacation_type);
CREATE INDEX vacation_requests_start_date_idx ON vacation_requests(start_date);
CREATE INDEX vacation_requests_end_date_idx ON vacation_requests(end_date);
