CREATE TABLE projects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL CHECK (name = btrim(name) AND name ~ '^[A-Za-z0-9]+$'),
    description VARCHAR(1000),
    ctime TIMESTAMP WITH TIME ZONE NOT NULL,
    utime TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE UNIQUE INDEX projects_name_lower_uq ON projects (lower(name));

CREATE TABLE project_members (
    project_id BIGINT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    user_account_id BIGINT NOT NULL REFERENCES user_accounts(id) ON DELETE CASCADE,
    PRIMARY KEY (project_id, user_account_id)
);

CREATE INDEX project_members_user_account_id_idx ON project_members(user_account_id);

CREATE TABLE project_manager (
    project_id BIGINT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    user_account_id BIGINT NOT NULL REFERENCES user_accounts(id) ON DELETE CASCADE,
    PRIMARY KEY (project_id, user_account_id)
);

CREATE INDEX project_manager_user_account_id_idx ON project_manager(user_account_id);
