
spring:
  application:
    name: vacation-sheet-service
  datasource:
    url: jdbc:postgresql://localhost:5432/vacation_sheet_db
    username: postgres
    password: postgres
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
  security:
    oauth2:
      client:
        registration:
          yandex:
            client-id: 2e08121a2d624f80b793ead6eeb9a365
            client-secret: 09e6fc1c4bcd43b69aaa1f427ef31d0f
#            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            redirect-uri: "http://localhost:8055/login/oauth2/code/yandex"
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_basic
            scope:
              - login:email
              - login:info
        provider:
          yandex:
            authorization-uri: https://oauth.yandex.ru/authorize
            token-uri: https://oauth.yandex.ru/token
            user-info-uri: https://login.yandex.ru/info?format=json
            user-name-attribute: id

server:
  port: 8055

  forward-headers-strategy: framework
  servlet:
    session:
      cookie:
        http-only: true
        same-site: lax

management:
  endpoints:
    web:
      exposure:
        include: health,info

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    csrf:
      enabled: true
      cookie-name: XSRF-TOKEN
      header-name: X-XSRF-TOKEN

app:
  security:
    allowed-email-domain: ""
